server:
  port: 8080
  contextPath: /
jwt:
  header: Authorization
  secret: O//ps230mBKaxQzmYJA3BFJsg5BKlBjVYfh01S01+lY=
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh
datasource:
  nosql:
    mongodb:
      host: localhost
      port: 27017
      database: test
spring:
  social:
    facebook:
      appId: <app-id>
      appSecret: <app-secret>
  session:
    store-type: jdbc
    jdbc: 
      schema: classpath:org/springframework/session/jdbc/schema-h2.sql
      table-name: SPRING_SESSION
app:
  facebook:
    images:
      path: facebook/media
      extension: jpg
      tumbnailTargetWidth: 356
      tumbnailTargetHeight: 280
    albums:
      pageSize: 9
    photos:
      pageSize: 12
    pagesToShow: 10  
    defaultPageSize: 25
---
spring:
  profiles: dev,default
  datasource:
    url: jdbc:h2:mem:FacebookPhotosSecurityDB;DB_CLOSE_DELAY=-1
    username: SA
    password:
    driverClassName: org.h2.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: create-drop
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect
---
spring:
  profiles: prod
  datasource: 
    url: jdbc:mysql://localhost:3306/FacebookPhotosSecurityDB
    username: root
    password: <mysql-password>
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect